downgraded ES version to 6.3

diff --git a/elasticsearch-6.8.0/bin/elasticsearch-env b/elasticsearch-6.8.0/bin/elasticsearch-env
--- a/elasticsearch-6.8.0/bin/elasticsearch-env
+++ b/elasticsearch-6.8.0/bin/elasticsearch-env
@@ -41,12 +41,11 @@ if [ -x "$JAVA_HOME/bin/java" ]; then
 else
   set +e
   JAVA=`which java`
-  echo "warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME"
   set -e
 fi
 
 if [ ! -x "$JAVA" ]; then
-  echo "could not find java; set JAVA_HOME" >&2
+  echo "could not find java; set JAVA_HOME or ensure java is in PATH"
   exit 1
 fi
 
@@ -64,7 +63,7 @@ if [ ! -z "$JAVA_OPTS" ]; then
 fi
 
 # check the Java version
-"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.java_version_checker.JavaVersionChecker
+"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.JavaVersionChecker
 
 export HOSTNAME=$HOSTNAME
 
@@ -82,5 +81,13 @@ ES_DISTRIBUTION_FLAVOR=default
 ES_DISTRIBUTION_TYPE=zip
 
 if [ -z "$ES_TMPDIR" ]; then
-  ES_TMPDIR=`"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.TempDirectory`
+  set +e
+  mktemp --version 2>&1 | grep coreutils > /dev/null
+  mktemp_coreutils=$?
+  set -e
+  if [ $mktemp_coreutils -eq 0 ]; then
+    ES_TMPDIR=`mktemp -d --tmpdir "elasticsearch.XXXXXXXX"`
+  else
+    ES_TMPDIR=`mktemp -d -t elasticsearch`
+  fi
 fi
